### ISSUE TITLE
additional playground resource ?

### ISSUE THREAD

**Issue by therealadityashankar** [ayushi7rawat/Ultimate-Python-Resource-Hub#2]
Hi Ayushi,

I've a code project called wc-code, https://github.com/vanillawc/wc-code,

if you copy the minimal example (below) in a text file and run a file server on it (like `python3 -m http.server`, this will not work without a web server), you'll see a default python interactive workspace,

```html
<!DOCTYPE html>
<head>
<script type="module" src="https://cdn.jsdelivr.net/gh/vanillawc/wc-code@1.0.3/src/wc-code.js"></script>
</head>
<body>
  <wc-code mode="python">
    <script type="wc-content">
       language = "python"
       what_is_it = "the coolest"
       print(f"{language} is {what_is_it}")
    </script>
  </wc-code>                                                                                         
</body>
```

I use these extensively on [my website](https://adityashankar.xyz/study/python/introduction-to-python) for coding tutorials, 
(all the blocks with "run-code" in them which allow running python code, they're wc-code instances, it takes some time to load the interpreter since its python running in your browser, literally, these are essentially pyodide instances, another project you should definitely add here too), 

I was hoping if you could add this resource to the link, that'd be really cool

**Comment by therealadityashankar** [comment]
you''ve to run a webserver to run it since it uses wasm to run python in the browser and simply opening an html file can't do that

**Comment by ayushi7rawat** [comment]
Please refer to the CODE OF CONDUCT.md and CONTRIBUTING.md
